name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: A clear and concise description of what the bug is.
      # value: ""
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behaviour
      placeholder: Steps to reproduce the behaviour
      value: |-
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.
      # value: ""
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: If applicable, add screenshots to help explain your problem.
      # value: ""
    validations:
      required: false
  - type: textarea
    id: attempted-fixes
    attributes:
      label: Attempted Fixes
      description: A list of things you have tried to fix the problem, including search engine links.
      placeholder: A list of things you have tried to fix the problem, including search engine links.
      # value: ""
    validations:
      required: false
  - type: textarea
    id: systemetails
    attributes:
      label: System Details
      description: Please add the output of `wails doctor`.
      render: shell
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Add any other context about the problem here.
      # value: ""
    validations:
      required: false

  # - type: markdown
  #   attributes:
  #     value: |
  #       Thanks for taking the time to fill out this bug report!
  # - type: input
  #   id: contact
  #   attributes:
  #     label: Contact Details
  #     description: How can we get in touch with you if we need more info?
  #     placeholder: ex. email@example.com
  #   validations:
  #     required: false
  # - type: textarea
  #   id: what-happened
  #   attributes:
  #     label: What happened?
  #     description: Also tell us, what did you expect to happen?
  #     placeholder: Tell us what you see!
  #     value: "A bug happened!"
  #   validations:
  #     required: true
  # - type: dropdown
  #   id: version
  #   attributes:
  #     label: Version
  #     description: What version of our software are you running?
  #     options:
  #       - 1.0.2 (Default)
  #       - 1.0.3 (Edge)
  #   validations:
  #     required: true
  # - type: dropdown
  #   id: browsers
  #   attributes:
  #     label: What browsers are you seeing the problem on?
  #     multiple: true
  #     options:
  #       - Firefox
  #       - Chrome
  #       - Safari
  #       - Microsoft Edge
  # - type: textarea
  #   id: logs
  #   attributes:
  #     label: Relevant log output
  #     description: Please copy and paste any relevant log output. 这将自动格式化为代码，因此无需背板。
  #     render: shell
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
