name: Feature Report
description: File a Feature report
title: "[Feature]: "
labels: ["feat", "triage"]
assignees:
  - octocat

body:
  - type: textarea
    id: descriptionn
    attributes:
      label: Description
      description: Description
      placeholder: A clear and concise description of what the bug is.
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: reproducen
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behaviour
      placeholder: Description
      value: |-
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: wails-doctorn
    attributes:
      label: System Details
      description: Please add the output of `wails doctor`.
      render: shell

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contactn
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happenedn
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: versionn
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsersn
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logsn
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. 这将自动格式化为代码，因此无需背板。
      render: shell
  - type: checkboxes
    id: termsn
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
